name: Publish Docker

on:
  push:
    branches:
      - saga
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      NCS_REVISION:
        description: 'nRF Connect SDK version'

env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build image
        run: |
          docker build --build-arg NCS_REVISION=$INPUT_NCS_REVISION -t coderbyheart/fw-nrfconnect-nrf-docker:$INPUT_NCS_REVISION .

      - name: Build asset_tracker application
        run: |
          docker run --rm -v ${PWD}:/workdir \
            coderbyheart/fw-nrfconnect-nrf-docker:$INPUT_NCS_REVISION \
            west build -p always -b nrf9160dk_nrf9160ns --build-dir /workdir/build/ /ncs/nrf/applications/asset_tracker

      - uses: actions/upload-artifact@v2
        with:
          name: asset_tracker
          path: |
            build/zephyr/merged.hex
            build/zephyr/app_update.bin

      - name: Publish image
        run: |
          cd nrf
          docker login -u coderbyheart -p $DOCKER_PASSWORD
          docker images
          docker push coderbyheart/fw-nrfconnect-nrf-docker
