name: Verify Dockerfile

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build image
        run: |
          docker build -t coderbyheart/fw-nrfconnect-nrf-docker .
      - name: Build asset_tracker application
        run: |
          docker run --rm \
            coderbyheart/fw-nrfconnect-nrf-docker \
            west build -p always -b nrf9160dk_nrf9160ns /ncs/nrf/applications/asset_tracker
